// Code generated by MockGen. DO NOT EDIT.
// Source: internal/wrap/discovery.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	host "github.com/libp2p/go-libp2p-core/host"
	mdns "github.com/libp2p/go-libp2p/p2p/discovery/mdns"
)

// MockDiscoverer is a mock of Discoverer interface.
type MockDiscoverer struct {
	ctrl     *gomock.Controller
	recorder *MockDiscovererMockRecorder
}

// MockDiscovererMockRecorder is the mock recorder for MockDiscoverer.
type MockDiscovererMockRecorder struct {
	mock *MockDiscoverer
}

// NewMockDiscoverer creates a new mock instance.
func NewMockDiscoverer(ctrl *gomock.Controller) *MockDiscoverer {
	mock := &MockDiscoverer{ctrl: ctrl}
	mock.recorder = &MockDiscovererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscoverer) EXPECT() *MockDiscovererMockRecorder {
	return m.recorder
}

// NewMdnsService mocks base method.
func (m *MockDiscoverer) NewMdnsService(peerhost host.Host, serviceTag string, notifee mdns.Notifee) mdns.Service {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewMdnsService", peerhost, serviceTag, notifee)
	ret0, _ := ret[0].(mdns.Service)
	return ret0
}

// NewMdnsService indicates an expected call of NewMdnsService.
func (mr *MockDiscovererMockRecorder) NewMdnsService(peerhost, serviceTag, notifee interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMdnsService", reflect.TypeOf((*MockDiscoverer)(nil).NewMdnsService), peerhost, serviceTag, notifee)
}
