// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/p2p_discovery.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	host "github.com/libp2p/go-libp2p-core/host"
	discovery "github.com/libp2p/go-libp2p/p2p/discovery"
)

// MockDiscoverer is a mock of Discoverer interface
type MockDiscoverer struct {
	ctrl     *gomock.Controller
	recorder *MockDiscovererMockRecorder
}

// MockDiscovererMockRecorder is the mock recorder for MockDiscoverer
type MockDiscovererMockRecorder struct {
	mock *MockDiscoverer
}

// NewMockDiscoverer creates a new mock instance
func NewMockDiscoverer(ctrl *gomock.Controller) *MockDiscoverer {
	mock := &MockDiscoverer{ctrl: ctrl}
	mock.recorder = &MockDiscovererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDiscoverer) EXPECT() *MockDiscovererMockRecorder {
	return m.recorder
}

// NewMdnsService mocks base method
func (m *MockDiscoverer) NewMdnsService(ctx context.Context, peerhost host.Host, interval time.Duration, serviceTag string) (discovery.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewMdnsService", ctx, peerhost, interval, serviceTag)
	ret0, _ := ret[0].(discovery.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewMdnsService indicates an expected call of NewMdnsService
func (mr *MockDiscovererMockRecorder) NewMdnsService(ctx, peerhost, interval, serviceTag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMdnsService", reflect.TypeOf((*MockDiscoverer)(nil).NewMdnsService), ctx, peerhost, interval, serviceTag)
}

// MockDiscoveryService is a mock of DiscoveryService interface
type MockDiscoveryService struct {
	ctrl     *gomock.Controller
	recorder *MockDiscoveryServiceMockRecorder
}

// MockDiscoveryServiceMockRecorder is the mock recorder for MockDiscoveryService
type MockDiscoveryServiceMockRecorder struct {
	mock *MockDiscoveryService
}

// NewMockDiscoveryService creates a new mock instance
func NewMockDiscoveryService(ctrl *gomock.Controller) *MockDiscoveryService {
	mock := &MockDiscoveryService{ctrl: ctrl}
	mock.recorder = &MockDiscoveryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDiscoveryService) EXPECT() *MockDiscoveryServiceMockRecorder {
	return m.recorder
}

// Close mocks base method
func (m *MockDiscoveryService) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockDiscoveryServiceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDiscoveryService)(nil).Close))
}

// RegisterNotifee mocks base method
func (m *MockDiscoveryService) RegisterNotifee(arg0 discovery.Notifee) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterNotifee", arg0)
}

// RegisterNotifee indicates an expected call of RegisterNotifee
func (mr *MockDiscoveryServiceMockRecorder) RegisterNotifee(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterNotifee", reflect.TypeOf((*MockDiscoveryService)(nil).RegisterNotifee), arg0)
}

// UnregisterNotifee mocks base method
func (m *MockDiscoveryService) UnregisterNotifee(arg0 discovery.Notifee) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnregisterNotifee", arg0)
}

// UnregisterNotifee indicates an expected call of UnregisterNotifee
func (mr *MockDiscoveryServiceMockRecorder) UnregisterNotifee(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterNotifee", reflect.TypeOf((*MockDiscoveryService)(nil).UnregisterNotifee), arg0)
}
