on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release
jobs:
  release:
    name: Building Release
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository...
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # required for the changelog to work correctly
      - name: Setting up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Runnig GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v0.157.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_REPO_SCOPE }}
